services:
  brain-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brain-agriculture-api
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Sobrescreve a Váriavel ENV para apontar pro host correto no Docker
      DATABASE_URL: postgresql://postgres:password@postgres:5432/brain_agriculture?schema=public

  postgres:
    image: postgres:15-alpine
    container_name: brain-agriculture-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: brain_agriculture
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
